name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:

      - name: Run Linter
        run: |
          run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            golangci/golangci-lint:v1.64.5 \
            golangci-lint run -v --disable errcheck --timeout 5m
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-api-service .

      - name: Stop old container
        run: docker stop api-container || true && docker rm api-container || true

      - name: Run Container
        run: |
          docker run -d \
            --name api-container \
            --network="host" \
            -e DB_HOST=localhost \
            -e DB_PORT=5432 \
            -e DB_USER=postgres \
            -e DB_PASSWORD=postgres \
            -e DB_NAME=testdb \
            -e DB_SSLMODE=disable \
            my-api-service
